package backends

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/uuid"

	pb "github.com/benjaminabbitt/scm/internal/lm/grpc"
)

const (
	// SCMContextDir is the directory for SCM-managed files
	SCMContextDir = ".scm"
	// SCMSessionsDir is the subdirectory for session-scoped context files
	SCMSessionsDir = ".scm/sessions"
	// SCMContextIDEnv is the environment variable for the session context ID
	SCMContextIDEnv = "SCM_CONTEXT_ID"
	// SessionFileMaxAge is the maximum age of session files before cleanup (24 hours)
	SessionFileMaxAge = 24 * time.Hour
)

// SessionContext holds information about a session's context.
type SessionContext struct {
	ID      string // Unique session identifier
	Path    string // Path to the session context file
	Content string // The assembled context content
}

// NewSessionContext creates a new session context with a unique ID.
func NewSessionContext() *SessionContext {
	return &SessionContext{
		ID: uuid.New().String(),
	}
}

// WriteSessionContext writes the assembled context to a session-scoped file.
// Returns the session context with the file path populated.
// workDir is the directory where the .scm/sessions/ directory will be created.
func WriteSessionContext(workDir string, fragments []*pb.Fragment) (*SessionContext, error) {
	session := NewSessionContext()

	// Assemble the context content
	var parts []string
	for _, f := range fragments {
		if f.Content == "" {
			continue
		}
		parts = append(parts, strings.TrimSpace(f.Content))
	}

	if len(parts) == 0 {
		// No content - return empty session (no file written)
		return session, nil
	}

	session.Content = "<!-- DO NOT EDIT: This file is auto-generated by `scm run`. Edit source fragments instead. -->\n\n" +
		strings.Join(parts, "\n\n---\n\n")

	// Ensure sessions directory exists
	sessionsDir := filepath.Join(workDir, SCMSessionsDir)
	if err := os.MkdirAll(sessionsDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create %s directory: %w", SCMSessionsDir, err)
	}

	// Write session context file
	session.Path = filepath.Join(sessionsDir, session.ID+".md")
	if err := os.WriteFile(session.Path, []byte(session.Content), 0644); err != nil {
		return nil, fmt.Errorf("failed to write session context: %w", err)
	}

	// Clean up old session files (best effort)
	cleanupOldSessions(sessionsDir)

	return session, nil
}

// ReadSessionContext reads context from the session file identified by SCM_CONTEXT_ID env var.
// Returns empty string if no session ID is set or file doesn't exist.
func ReadSessionContext(workDir string) (string, error) {
	sessionID := os.Getenv(SCMContextIDEnv)
	if sessionID == "" {
		return "", nil
	}

	sessionPath := filepath.Join(workDir, SCMSessionsDir, sessionID+".md")
	content, err := os.ReadFile(sessionPath)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("failed to read session context: %w", err)
	}

	return string(content), nil
}

// CleanupSessionContext removes the session context file for the given session ID.
func CleanupSessionContext(workDir, sessionID string) error {
	if sessionID == "" {
		return nil
	}
	sessionPath := filepath.Join(workDir, SCMSessionsDir, sessionID+".md")
	if err := os.Remove(sessionPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to cleanup session context: %w", err)
	}
	return nil
}

// cleanupOldSessions removes session files older than SessionFileMaxAge.
func cleanupOldSessions(sessionsDir string) {
	entries, err := os.ReadDir(sessionsDir)
	if err != nil {
		return
	}

	cutoff := time.Now().Add(-SessionFileMaxAge)
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			continue
		}
		if info.ModTime().Before(cutoff) {
			os.Remove(filepath.Join(sessionsDir, entry.Name()))
		}
	}
}

